### ISSUE TITLE
Can't connect to server automatically

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#195] opened 2021-08-18 15:13 UTC
After installing leoInteg as you requested I can only connect to the server in two steps:

Step 1: automatically start the server, but do *not* automatically connect to the server.
Step 2: connect to the server by hand (using the connect button).

If I change the setting to automatically start *and* connect to the server, I get an endless "connecting" message even though the server clearly has started.  

### Addendum: 
_Workaround added here for visibility by Félix:_
turns out that having the 'python command' leointeg setting **point to a .cmd/.bat batch** file prevents leointeg from picking up the stdout of the spawned process. **The workaround is to make that 'command' setting point to the python executable** itself rather than a batch file pointing to it.

**Comment by boltex** [comment] 2021-09-05 03:04
@edreamleo I forgot to document and assign this issue properly. but I think It's solved since the last beta 0.1.18 and/or it was a server issue, which was also fixed indirectly. 

Could you re-check and see if this can be closed?

**Comment by edreamleo** [comment] 2021-09-06 13:50
On Sat, Sep 4, 2021 at 10:04 PM Felix ***@***.***> wrote:

> @edreamleo <https://github.com/edreamleo> I forgot to document and assign
> this issue properly. but I think It's solved since the last beta 0.1.18
> and/or it was a server issue, which was also fixed indirectly.
>
> Could you re-check and see if this can be closed?
>
Still no joy. It seems to take a *long* to start the server by hand, so
connecting automatically doesn't work.

We can zoom about this if you like.

Edward

**Comment by boltex** [comment] 2021-09-06 17:27
@edreamleo  Oh I remember now: The way (or the command used) to start the server is not picked up in the stdout, so the string emited by the server to signal that it had started is not picked up. I cannot reproduce this problem so it must be related to the 'python  launch' command you gave in the settings to start the server.

Can you provide the exact command you're launching the server with in your leointeg config?

(i could also solve this with simply using an arbitrary timer, lets say 5 seconds, to consider the server started if nothing was detected on the stdout... - only drawback is that tere would be no 'leo bridge server' output panel in leointeg.)

I had setup a (tiny) vscode-extension  to experiment with grabbing the stdout of a spawned process : https://github.com/boltex/test-spawn ... I will re-use it by modifying it a little bit to test for solutions to this problem.

It is so tiny that i think you migth enjoy looking at it . (clone it, run 'npm i'  and press F5 in vscode to launch it - same drill as any other extension) all the code is in 'index.js' which i think you could understand.

**Comment by boltex** [comment] 2021-09-07 01:56
After verifications with Edward, it turns out that having the **'python command'** leointeg setting point to a .cmd/.bat batch file prevents leointeg from picking up the stdout of the spawned process. **The workaround is to make that 'command' setting point to the python executable itself rather than a batch file pointing to it.**

![leoserveroptions](https://user-images.githubusercontent.com/847716/132272474-d8a81dad-42b6-40a9-a24c-9a24ababf7ba.png)

I've added the 'not sure' tag to this issue and I'll also put this link here to the https://github.com/boltex/test-spawn2 small  extension project dedicated to trying out solutions for picking up the stdout of a spawned process from nodejs where the process is a  batch file being run by the os.

**Comment by boltex** [comment] 2021-09-19 18:13
Solved this way/Workaround: Python command should point to the executable, **not** to a batch file launching the executable.

**Closed by boltex** 2021-09-19 18:13 UTC
Labels: bug, Not Sure...
